"""Branded macOS viewer: the GUI window carries Scripto's name and icon.

flet's desktop runtime opens the window with a cached, generic "Flet.app"
client — so the Dock shows a second, foreign icon next to the launcher.
Before starting the GUI we copy that client once per flet-desktop version,
rename it to Scripto, swap in our icon, re-sign it ad-hoc and point
``FLET_VIEW_PATH`` at the copy. Every failure falls back to the stock
viewer: branding must never block a launch.
"""

from __future__ import annotations

import logging
import os
import plistlib
import shutil
import subprocess
import sys
from pathlib import Path

from . import update
from .paths import data_dir

logger = logging.getLogger(__name__)

VIEWER_APP_NAME = "Scripto.app"


def ensure_branded_viewer() -> Path | None:
    """Directory to use as FLET_VIEW_PATH; None = keep the stock viewer."""
    if sys.platform != "darwin":
        return None
    try:
        return _build_if_needed()
    except Exception:
        logger.warning("viewer branding failed; using the stock Flet viewer",
                       exc_info=True)
        return None


def rebrand_bundle(app: Path, icon: Path | None) -> None:
    """Renames a copied viewer bundle to Scripto and swaps its icon file.

    Pure file surgery (no signing) so it is testable on any platform.
    """
    info_path = app / "Contents/Info.plist"
    info = plistlib.loads(info_path.read_bytes())
    info["CFBundleName"] = "Scripto"
    info["CFBundleDisplayName"] = "Scripto"
    info["CFBundleIdentifier"] = "local.scripto.viewer"
    info_path.write_bytes(plistlib.dumps(info))
    if icon is not None:
        icon_name = str(info.get("CFBundleIconFile", "AppIcon"))
        if not icon_name.endswith(".icns"):
            icon_name += ".icns"
        shutil.copyfile(icon, app / "Contents/Resources" / icon_name)


def _build_if_needed() -> Path | None:
    from flet_desktop import ensure_client_cached

    source_dir = Path(ensure_client_cached())
    source_app = next(
        (source_dir / name for name in os.listdir(source_dir)
         if name.endswith(".app")),
        None,
    )
    if source_app is None:
        return None

    # Keyed by the cache-dir name (e.g. flet-desktop-full-0.86.0): a flet
    # upgrade via `uv sync` gets a fresh copy, old versions are pruned.
    viewers = data_dir() / "viewer"
    dest = viewers / source_dir.name
    if (dest / VIEWER_APP_NAME / "Contents/MacOS").is_dir():
        return dest

    work = dest.with_name(dest.name + ".tmp")
    shutil.rmtree(work, ignore_errors=True)
    work.mkdir(parents=True)
    app = work / VIEWER_APP_NAME
    # ditto preserves signatures/xattrs of everything we do not touch.
    _run("ditto", str(source_app), str(app))
    rebrand_bundle(app, _make_icns(work))
    # The plist edit invalidated the signature; a fresh ad-hoc one is
    # required for the bundle to launch at all on Apple silicon.
    _run("codesign", "--force", "--deep", "-s", "-", str(app))

    shutil.rmtree(dest, ignore_errors=True)
    work.rename(dest)
    for old in viewers.iterdir():
        if old != dest:
            shutil.rmtree(old, ignore_errors=True)
    return dest


def _make_icns(work: Path) -> Path | None:
    """Scripto's icon as .icns, generated by the repo's icon script; None
    (keep the stock icon) when not running from a checkout."""
    root = update.repo_root()
    generator = (root / "launchers/macos/make_icon.py") if root else None
    if generator is None or not generator.is_file():
        return None
    iconset = work / "AppIcon.iconset"
    _run(sys.executable, str(generator), str(iconset))
    icns = work / "AppIcon.icns"
    _run("iconutil", "-c", "icns", str(iconset), "-o", str(icns))
    return icns


def _run(*args: str) -> None:
    subprocess.run(list(args), check=True, capture_output=True, timeout=120)
